### PR TITLE
Rider driver communication

### PR DESCRIPTION
**Pull request by Madeeha-Anjum**
image
image
image
image

### CODE REVIEW

**Comment by LukeDelaCruz** [comment]
Not a reviewer for this so I won't comment on code quality, but I need to be clear on a few things here:

**Comment by LukeDelaCruz** [comment]
Not a reviewer for this so I won't comment on code quality, but I need to be clear on a few things here:

- is the reason for generating a new trip document each time because _FB listeners get "confused"_ or you _want to keep a history of trips (which is not a requirement afaik)_? 
- Let's change the state **COMMING** to **DRIVER_PICKING_UP**

- lastly, should MapActivity.java just get updates right out of the box? Or do we have to adapt it to follow your 3 requirements? Because I am running this but not getting updates on MapActivity now inside your ```onTripStatusUpdate``` method

**Comment by Madeeha-Anjum** [comment]
1) "[US 06.01.01] As a driver, I want to see requests that I already accepted while offline."- I might be missunderstanding this but this one uses the word "requests" so like history so then we know that a driver can only accept 1 request so this one means keep a history of past requests. This is what I thought but I might be wrong in which cause as long as the trip id's are unique my code works. 

2) sure we can change on route, 

3) The reason my code won't show u anything is beacse the status never changed. What u need to do is when a driver accepts the request you need to 1) set the trip session and a listener and 3*****change the trip request status on firebase. 
-the way I did it was I went onto firebase and manually changed the status and checked and tested all the states.

**Comment by LukeDelaCruz** [comment]
1. [US 06.01.01] ticket means that a driver can see all the requests he's accepted (on the current trip list). Meaning that a driver can accept multiple ride requests on our current trip list (stored in our Trips collection).

We don't need to create a history of ALL trips afaik. I think there's a misunderstanding on what this ticket means.
Also, it's offline just in case that driver loses internet connection.

The reason why we're concerned about having so many trips is we've found it very difficult to search a collection by ID on firebase without having to do hacky things.

**Comment by Madeeha-Anjum** [comment]
"The reason why we're concerned about having so many trips is we've found it very difficult to search a collection by ID on firebase without having to do hacky things." 
- not sure what u mean by this, but I think it might be because once the Trip is created it is put into firebase and never taken out so the document ids are not attached to the objects but I added one line in createtrip() in DBManager to make the id attached to the object so now it should be much easier to search to the collection by id
Side note create an account also has this problem and the one line should be added there to.


As for   [US 06.01.01] ticket
image
My code was done ina way that the driver has only one trip as I assumed this was what the requirement was but now that it seems I was wrong about that my code would need to be changed a little. 
The code would need to allow the ability to set multiple session trips and notify the code to add a listener to multiple trips.

**Pull request closed without merging**
